### ISSUE TITLE
Portfile Xcode flag

### ISSUE THREAD

**Issue by satraul** [satraul/macports-base#6]
Portfile should support use_xcode, a flag for Xcode dependency.
```tcl
# Portfile
...
use_zip yes
use_configure no
use_xcode yes
extract.mkdir yes
...
```
Then, when port build (a port1.0 target action) is run, this flag is checked and warnings and/or errors are issued correspondingly.
```tcl
# src/port1.0/portbuild.tcl
...
# define options
options build.asroot \
        build.jobs \
        build.target \
        use_parallel_build \
        use_xcode \
        use_xcode_clt
...
if​ { [tbool use_xcode] && ![tbool xcodeInstalled] } {
    ​return​ -code ​error​ ​"Xcode was not found on this system!"
}
...
```

**Comment by satraul** [comment]
Reference: https://github.com/satraul/macports-base/commit/a75a879896d5275398bbb19c969e5157fb37fe37

I've implemented the use_xcode flag like this:

In port build, it checks returns error if {[option use_xcode yes] && [$xcodebuildcmd eq "none"]}. The $xcodebuildcmd variable is set by the macports::setxcodeinfo proc from macports1.0. I assume this is reliable.

While tinkering with port build, I noticed that the portbuild::build_getmaketype proc runs several times for a port (I built hexfiend). I don't understand, why is this?

Regarding "build.type flag", I searched for "build.type xcode". It's only used in the "xcode 1.0" group (142 matches). There's also the xcodeversion 1.0 group (54 matches) but it doesn't set build.type, only checks Xcode version. Even though the it's relevant, the use_xcode flag should be independent from these groups right?

**Comment by satraul** [comment]
Since checking only if $xcodebuildcmd exists isn't reliable enough, I drafted some other ways we could check if Xcode is installed or not:
```tcl
# 1st way: check if xcodebuild exists. Unreliable because it could be a shim
global xcodebuildcmd
if {xcodebuildcmd ne none} {
    return true
}
return false
```
```tcl
# 2nd way: check if xcodebuild -version prints version
global xcodeversion
if {xcodeversion ne none} {
    return true
}
return false
```
```tcl
# 3rd way: check if xcode-select prints path
global developer_dir
if {[info exists developer_dir] && [developer_dir ne ""]} {
    return true
}
return false
```
```tcl
# 4th way: check if xcode-select prints path and it's not CLT
global developer_dir
if {[info exists developer_dir] && [developer_dir ne ""] && [developer_dir ne "/Library/Developer/CommandLineTools"]}
    return true
}
return false
```
```tcl
# 5th way: 4th way + also check for valid Xcode directories outside xcode-select. Code taken from macports::set_developer_dir

global developer_dir
if {[info exists developer_dir] && [developer_dir ne ""] && [developer_dir ne "/Library/Developer/CommandLineTools"]}
    return true
}

set installed_xcodes {}
try -pass_signal {
    set mdfind [findBinary mdfind $macports::autoconf::mdfind_path]
    set installed_xcodes [exec $mdfind "kMDItemCFBundleIdentifier == 'com.apple.Xcode' || kMDItemCFBundleIdentifier == 'com.apple.dt.Xcode'"]
} catch {*} {}

foreach app {/Applications/Xcode.app /Developer/Applications/Xcode.app} {
    if {[file isdirectory $app]} {
        lappend installed_xcodes $app
    }
}

set installed_xcodes [lsort -unique $installed_xcodes]

try -pass_signal {
    if {[llength $installed_xcodes] == 0} {
        return false
    }
    set mdls [findBinary mdls $macports::autoconf::mdls_path]
    foreach xcode $installed_xcodes {
        set vers [exec $mdls -raw -name kMDItemVersion $xcode]
        if {$vers eq {(null)}} {set vers unknown}
        if {[_is_valid_developer_dir ${xcode}/Contents/Developer]} {
            # ${xcode}/Contents/Developer found (was not selected by xcode-select)
            return true
        } elseif {[vercmp $vers 4.3] >= 0} {
            # xcode >= 4.3 found
            return true
        } elseif {[_is_valid_developer_dir ${xcode}/../..]} {
            # xcode < 4.3 found
            return true
        } else {
            return false
        }
    }
} catch {*} {}
return false
```

**Comment by satraul** [comment]
Answer to why the `portbuild::build_getmaketype` proc runs multiple times:
That proc is called in the outermost level of `portbuild.tcl`. This means the proc runs for every file that requires port build, it also runs multiple times for every dependency that needs to build.

For my modified HexFiend with `use_xcode yes`, I checked to verify that it should be `use_xcode no` for it's dependencies with some debug code:
```Tcl
...
proc portbuild::build_getmaketype {args} {
    global xcodebuildcmd subport
    set level [expr {[info level]}]
    ui_msg "subport: $subport; use_xcode: [option use_xcode]; info level: $level; info cmdcount [info cmdcount]"
    ui_msg "clock: [clock format [clock seconds]]"
...
```
which outputs 
```
--->  Building HexFiend
subport: HexFiend; use_xcode: yes; info level: 1; info cmdcount 50427
clock: Wed May 29 22:35:43 WIB 2019
subport: HexFiend; use_xcode: yes; info level: 1; info cmdcount 52470
clock: Wed May 29 22:35:43 WIB 2019
subport: HexFiend; use_xcode: yes; info level: 1; info cmdcount 52625
clock: Wed May 29 22:35:43 WIB 2019
subport: HexFiend; use_xcode: yes; info level: 1; info cmdcount 53484
clock: Wed May 29 22:35:51 WIB 2019
subport: HexFiend; use_xcode: yes; info level: 1; info cmdcount 53754
clock: Wed May 29 22:35:51 WIB 2019
subport: HexFiend; use_xcode: yes; info level: 1; info cmdcount 53909
clock: Wed May 29 22:35:51 WIB 2019
```
So all `$subport` outputted the HexFiend each time. I also expected the level to be different since the main caller should be from a different file. Didn't prove that it's `use_xcode no` for dependencies, but we'll assume it is and move on.

**Comment by satraul** [comment]
To later create source for portfile.7.txt we could use [doclifter](http://www.catb.org/~esr/doclifter/) which converts man pages to DocBook. [macports-port/doclifter](https://github.com/macports/macports-ports/blob/master/textproc/doclifter/Portfile)

**Comment by neverpanic** [comment]
Hm, so it seems that `portbuild::build_getmaketype` is actually called multiple times while building a port. It's possible that this happens because we've attached what's called a "variable trace" to a variable, which basically means a proc gets executed every time a variable is read (and that variable might be used multiple times in the build process).

You could look at the stack trace to find out where these multiple calls are, e.g. if you use this code:
```tcl
catch {invalid_command}
ui_debug $::errorInfo
```
This is a hack and there are more programmatic ways to read the current stack, but this works just fine for debugging purposes. See also https://stackoverflow.com/questions/2193731/stack-trace-info-in-errorinfo-in-tcl.

I think approach no. 4 should be detailed enough to check for an Xcode installation. It's probably not unreasonable for us to expect the Xcode installation to be selected as `developer_dir` when people want to build ports that use Xcode.

As for the manpage conversion, our ideal target format is asciidoc, so using doclifter to convert it to DocBook gets you halfway there if you then use other tools to convert DocBook to asciidoc. For the guide, we have considered docbookrx for this task (see https://trac.macports.org/ticket/56046)

**Comment by satraul** [comment]
I've tried the stack trace approach putting a simple
```tcl
try {
    error "Yup, an error"
} catch {*} {
    ui_msg $::errorInfo
}
```
but it all prints 
```tcl
"error "Yup, an error""
    ("uplevel" body line 2)
    invoked from within
"uplevel 1 $body"
```
I don't understand this yet, should be catching a proc instead like the stackoverflow link?

**Comment by satraul** [comment]
This issue is done, closing after approval

**Comment by neverpanic** [comment]
> I don't understand this yet, should be catching a proc instead like the stackoverflow link?

I think that may be a side effect of how we're executing Portfiles, because we're creating a new interpreter to do that, and each new interpreter has its own stack, obviously. So what this is telling you, is that it's called somewhere inside the Portfile :/

Also note that we have our own implementation of try, so this may also be affecting the strack trace. I'd recommend you also try with the raw `catch` builtin instead.
