### ISSUE TITLE
Understand how to build without Xcode

### ISSUE THREAD

**Issue by satraul** [satraul/macports-base#7]
Investigate how to force /usr/lib/libxcselect.dylib to not select Xcode and how MacPorts build phase works in general.

**Comment by satraul** [comment]
So trace mode starts somewhere around here in `portutil.tcl`:
```tcl
  #start tracelib
  set tracing no
  if {($result == 0
    && [tbool ports_trace]
    && $target ne "clean"
    && $target ne "uninstall")} {
      # uninstall will open a portfile from registry and call
      # deactivate and uninstall there; if we enable trace mode
      # for the first level the two trace threads will conflict
      # and cause a deadlock.
      porttrace::trace_start $workpath

      # Enable the fence to prevent any creation/modification
      # outside the sandbox.
      if {$target ne "activate"
        && $target ne "deactivate"
        && $target ne "archive"
        && $target ne "install"} {
          porttrace::trace_enable_fence
      }
```
I haven't read the procs yet but `::trace_start` probably setup the sandbox, the `::trace_enable_fence` starts putting a fence (lol) around the sandbox to define which files can and cannot be modified.

To start, I will experiment with on the interaction between this fence and the output of `$xcodebuildcmd`, which currently outputs `/usr/bin/xcodebuild` on my Mac. If I can successfully restrict it, it then should reject building a port with `use_xcode yes`.

**Comment by neverpanic** [comment]
See `port1.0/porttrace.tcl`, it has documentation for `trace_start` and `trace_enable_fence`.

`trace_start` creates a new Tcl thread, which will eventually end up calling `tracelib run`, which is the server-side component of trace mode and implemented in `pextlib1.0/tracelib.c`. It also computes the sandbox boundaries and transmits them to the `tracelib` module using `tracelib setsandbox`.

`trace_enable_fence` just sets a boolean in `pextlib1.0/tracelib.c` that controls whether a allow-all sandbox or the configured sandbox is sent to client processes that are being traced, see `pextlib1.0/tracelib.c` line 552 and following.

**Comment by satraul** [comment]
Implemented a `PLACEHOLDER_DENY_XCODE` flag in `trace_start` in commit  https://github.com/satraul/macports-base/commit/fe8446a8ee2d41062ed6d66d2c44c718c58dc7f5 (WIP)

**Comment by satraul** [comment]
So I've tested it with `port build -t` on HexFiend. As expected it fails to build. It errors out weirdly though, what should be the expected behavior?
Logs for `PLACEHOLDER_DENY_XCODE yes`:
```
portbuild::build_getmaketype called
portbuild::build_getmaketype called
portbuild::build_getmaketype called
Error: Failed to build HexFiend: command execution failed
Error: See /opt/macports-test/var/macports/logs/_Users_satraul_git_macports-ports_editors_HexFiend/HexFiend/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port HexFiend failed
```
```
:info:build xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
```
Logs for PLACEHOLDER_DENY_XCODE no:
```
portbuild::build_getmaketype called
portbuild::build_getmaketype called
portbuild::build_getmaketype called
portbuild::build_getmaketype called
portbuild::build_getmaketype called
portbuild::build_getmaketype called
```
```
:info:build ** BUILD SUCCEEDED **
```
Also, an error found on both runs:
```
Error from thread tid0x7000016da000
can't read "PATH": no such variable
    while executing
"set macports::user_path "/Users/satraul/perl5/bin:/Users/satraul/anaconda3/condabin:$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/..."
```

**Comment by neverpanic** [comment]
We do expect the build to fail when trace mode is on and `use_xcode` is `no`, so that's not out of the ordinary. It's probably fine that it doesn't find `xcrun`, but we should probably force `developer_dir` to point to the command line tools when `use_xcode no` is set, i.e. it should consider `/Library/Developer/CommandLineTools` the active `developer_dir`.

**Comment by satraul** [comment]
[I just made a flow chart](https://github.com/satraul/macports-base/files/3265913/Xcode.flow.pdf) to visualize what I should submit in a PR for this month. Please take a look

**Comment by neverpanic** [comment]
Yes, flowchart looks good, that's exactly how this should behave.
